In [1]:
import os
import pandas as pd
import numpy as np
import json

In [9]:
df = pd.read_json('rules_valid.json')
df.T

           p                                             labels given
1       P462                                          [RoboCop]   sbj
2        P57                                          [RoboCop]   sbj
3        P17                                    [Event Cinemas]   sbj
4        P58                                      [Jim Sharman]   obj
5        P57  [Shock Treatment and The Rocky Horror Picture ...   sbj
...      ...                                                ...   ...
49663   P688  [tetracenomycin polyketide synthesis O-methylt...   obj
49665   P681  [Synapse differentiation-inducing gene protein 1]   sbj
49666  P1196                                [H. David Dalquist]   sbj
49667   P735                                [H. David Dalquist]   sbj
49668   P119                                [H. David Dalquist]   sbj

[45105 rows x 3 columns]

In [30]:
rule_ids = list(df.head(0))
rule_preds = list(df.T["p"])

In [7]:
path = "/mount/arbeitsdaten31/studenten1/dialog-system/2020/student_directories/Chang_Wentseng/"
df_dev = pd.read_json(path + 'data/csqa.dev.json')
df_dev

,id,tokens,relation,topic_tags,direction
0,1,"[[CLS], which, color, is, robocop, associated,...",P462,"[O, O, O, O, B_SBJ, O, O, O, O]",out
1,2,"[[CLS], which, person, directed, robocop, ?, [...",P57,"[O, O, O, O, B_SBJ, O, O]",out
2,3,"[[CLS], which, political, territory, is, event...",P17,"[O, O, O, O, O, B_SBJ, I_SBJ, O, O, O, O, O]",out
3,4,"[[CLS], which, works, of, art, are, jim, sharm...",P58,"[O, O, O, O, O, O, B_OBJ, I_OBJ, O, O, O, O, O]",in
4,5,"[[CLS], who, directed, shock, treatment, and, ...",P57,"[O, O, O, B_SBJ, I_SBJ, O, B_SBJ, I_SBJ, I_SBJ...",out
...,...,...,...,...,...
45071,49663,"[[CLS], what, is, the, nucleic, acid, sequence...",P688,"[O, O, O, O, O, O, O, O, O, O, O, B_OBJ, I_OBJ...",in
45072,49665,"[[CLS], which, cellular, components, are, comp...",P681,"[O, O, O, O, O, O, O, B_SBJ, I_SBJ, I_SBJ, I_S...",out
45073,49666,"[[CLS], what, situation, did, h, ., david, dal...",P1196,"[O, O, O, O, B_SBJ, I_SBJ, I_SBJ, I_SBJ, O, O,...",out
45074,49667,"[[CLS], what, is, forename, of, h, ., david, d...",P735,"[O, O, O, O, O, B_SBJ, I_SBJ, I_SBJ, I_SBJ, O, O]",out
45075,49668,"[[CLS], where, was, h, ., david, dalquist, bur...",P119,"[O, O, O, B_SBJ, I_SBJ, I_SBJ, I_SBJ, O, O, O]",out

In [33]:
gold_ids = list(df_dev["id"])
gold_preds = list(df_dev["relation"])

In [43]:
clean_ids = []
clean_preds = []
for ids in rule_ids:
    if ids in gold_ids:
        clean_ids.append(ids)
        clean_preds.append(df[ids][0])
print(len(clean_ids))
print(len(clean_preds))

45076
45076

In [44]:
d = {"rule_ids":clean_ids, "rule_preds":clean_preds, "gold_ids":gold_ids, "gold_preds":gold_preds}
compare = pd.DataFrame(data=d)
compare

       rule_ids rule_preds  gold_ids gold_preds
0             1       P462         1       P462
1             2        P57         2        P57
2             3        P17         3        P17
3             4        P58         4        P58
4             5        P57         5        P57
...         ...        ...       ...        ...
45071     49663       P688     49663       P688
45072     49665       P681     49665       P681
45073     49666      P1196     49666      P1196
45074     49667       P735     49667       P735
45075     49668       P119     49668       P119

[45076 rows x 4 columns]

In [115]:
drop_compare = compare.dropna()
drop_compare

       rule_ids rule_preds  gold_ids gold_preds
0             1       P462         1       P462
1             2        P57         2        P57
2             3        P17         3        P17
3             4        P58         4        P58
4             5        P57         5        P57
...         ...        ...       ...        ...
45071     49663       P688     49663       P688
45072     49665       P681     49665       P681
45073     49666      P1196     49666      P1196
45074     49667       P735     49667       P735
45075     49668       P119     49668       P119

[44438 rows x 4 columns]

In [46]:
tagset = pd.read_json(path + 'data/csqa_tags.json')
tagset

         0
0       P6
1       P7
2       P9
3      P16
4      P17
..     ...
276  P3179
277  P3195
278  P3279
279  P3301
280  P3320

[281 rows x 1 columns]

In [120]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
new_tagset = list(tagset[0])
le.fit(new_tagset)
gp = le.transform(drop_compare["gold_preds"])
gp
#list(le.inverse_transform(gp))

array([183, 207,  76, ...,  26, 241,  24])

tr_none = []
for i in d["rule_preds"]:
    if i == None:
        tr_none.append(str(i))
    else:
        tr_none.append(i)
tr_none

In [121]:
rp = le.transform(drop_compare["rule_preds"])
print(len(rp))
rp
#list(le.inverse_transform(rp))

44438

array([183, 207,  76, ...,  26, 241,  24])

In [122]:
from sklearn.metrics import f1_score
gold_preds = gp
rule_preds = rp
f1_score(gold_preds, rule_preds, average='macro')

0.970758933696582

In [130]:
uniq_tagset = []
for i in drop_compare["rule_preds"]:
    if i not in uniq_tagset:
        uniq_tagset.append(i)
len(uniq_tagset)

256

In [132]:
from sklearn.metrics import classification_report
gold_preds = gp
rule_preds = rp
uniq_tagset = uniq_tagset
print(classification_report(gold_preds, rule_preds, target_names=uniq_tagset))

              precision    recall  f1-score   support

        P462       1.00      1.00      1.00       246
         P57       1.00      1.00      1.00       245
         P17       1.00      0.99      1.00       775
         P58       1.00      1.00      1.00        35
        P682       1.00      0.57      0.73         7
        P703       1.00      1.00      1.00        46
        P161       1.00      1.00      1.00         2
        P176       1.00      1.00      1.00        60
        P264       0.95      1.00      0.97        69
        P750       1.00      1.00      1.00        36
        P136       0.93      0.96      0.95        27
        P123       1.00      1.00      1.00      2825
         P27       0.89      1.00      0.94        90
        P991       1.00      0.96      0.98        95
         P21       1.00      1.00      1.00       367
        P106       1.00      0.57      0.73         7
        P921       1.00      0.78      0.88         9
       P1412       1.00      1.00      1.00       180
        P702       1.00      1.00      1.00        41
        P641       1.00      1.00      1.00        19
         P54       1.00      0.94      0.97        16
        P463       1.00      1.00      1.00       299
        P119       1.00      1.00      1.00         1
       P1532       1.00      1.00      1.00       259
         P20       1.00      0.71      0.83         7
       P1196       1.00      1.00      1.00        21
        P162       1.00      0.95      0.98       147
        P344       1.00      1.00      1.00        14
        P512       0.96      0.98      0.97       220
        P937       1.00      1.00      1.00        18
        P166       1.00      1.00      1.00        72
        P108       1.00      1.00      1.00       258
         P19       0.91      0.79      0.84       354
        P551       1.00      0.99      1.00       159
       P1411       1.00      1.00      1.00        50
       P3279       1.00      1.00      1.00       523
         P40       0.99      1.00      0.99       155
        P138       0.96      0.86      0.91       285
         P39       1.00      0.99      1.00       420
        P112       1.00      1.00      1.00         1
        P425       0.76      1.00      0.86        16
        P710       1.00      1.00      1.00         1
        P610       1.00      1.00      1.00       216
       P1376       1.00      1.00      1.00         4
        P159       1.00      1.00      1.00        63
         P35       1.00      1.00      1.00        98
         P26       1.00      1.00      1.00       766
        P127       0.67      1.00      0.80         8
        P102       1.00      1.00      1.00        57
        P681       1.00      0.94      0.97        18
        P688       0.94      0.97      0.95        32
        P180       1.00      0.83      0.91         6
        P509       1.00      1.00      1.00        25
        P140       1.00      1.00      1.00       124
       P1071       0.97      1.00      0.99        72
        P144       1.00      1.00      1.00        49
       P1441       1.00      1.00      1.00         1
       P1454       1.00      1.00      1.00        20
        P414       1.00      1.00      1.00         1
        P931       0.99      1.00      0.99       159
       P2554       1.00      1.00      1.00        19
        P740       1.00      0.91      0.95        23
        P840       1.00      1.00      1.00         7
        P706       1.00      0.85      0.92       271
        P749       1.00      1.00      1.00         1
        P172       1.00      0.99      0.99       410
         P25       0.87      1.00      0.93       246
        P607       0.98      1.00      0.99       321
          P6       1.00      1.00      1.00       638
        P734       1.00      0.86      0.92         7
        P417       0.99      0.79      0.88       935
       P1346       0.88      0.91      0.89        98
        P276       1.00      1.00      1.00       122
        P137       1.00      1.00      1.00       117
         P69       1.00      1.00      1.00         7
        P364       0.97      0.94      0.95        94
         P22       1.00      1.00      1.00         7
        P163       1.00      0.76      0.86        78
        P611       1.00      1.00      1.00       123
        P194       1.00      1.00      1.00        59
       P1001       1.00      1.00      1.00        85
        P495       1.00      1.00      1.00        53
        P915       1.00      0.67      0.80         6
         P37       1.00      1.00      1.00        24
         P30       1.00      1.00      1.00      2189
        P190       1.00      1.00      1.00       328
        P366       0.93      0.45      0.61        31
       P1066       1.00      1.00      1.00         4
        P802       1.00      1.00      1.00       292
        P479       1.00      1.00      1.00        29
       P2515       1.00      1.00      1.00         4
       P1344       1.00      1.00      1.00         8
         P36       1.00      1.00      1.00        10
       P1040       1.00      1.00      1.00        27
       P2416       1.00      1.00      1.00      1362
         P85       0.50      1.00      0.67         1
        P767       1.00      1.00      1.00        11
        P361       1.00      1.00      1.00       179
        P355       1.00      1.00      1.00         1
        P452       1.00      1.00      1.00      2603
       P1542       0.88      0.88      0.88        25
        P680       0.62      0.62      0.62         8
       P1995       0.96      1.00      0.98       473
       P2175       1.00      1.00      1.00        30
        P800       1.00      1.00      1.00        20
        P101       1.00      0.97      0.98        59
        P175       1.00      0.99      1.00       140
        P291       0.88      0.74      0.80        58
        P206       1.00      1.00      1.00         2
       P1416       1.00      0.90      0.95       205
        P735       1.00      0.50      0.67         6
       P1313       1.00      1.00      1.00         2
        P684       1.00      0.77      0.87        30
         P53       1.00      1.00      1.00       479
        P466       1.00      1.00      1.00         1
       P1027       1.00      1.00      1.00       143
         P47       1.00      1.00      1.00         8
        P118       0.92      1.00      0.96      2103
       P1080       1.00      0.93      0.96        69
       P1434       0.99      0.85      0.91       265
        P793       1.00      1.00      1.00         6
        P129       1.00      1.00      1.00        25
        P664       1.00      1.00      1.00         1
       P1038       0.88      0.88      0.88        33
        P748       1.00      1.00      1.00        12
         P50       0.99      0.98      0.98       126
       P1142       0.75      1.00      0.86       294
       P1050       1.00      1.00      1.00         7
        P780       1.00      1.00      1.00         1
       P1435       1.00      1.00      1.00         3
        P859       1.00      1.00      1.00        15
        P400       1.00      1.00      1.00         1
        P410       1.00      1.00      1.00         2
        P170       1.00      1.00      1.00       171
        P186       1.00      1.00      1.00        41
        P609       1.00      1.00      1.00        38
        P241       0.88      0.96      0.92       313
        P676       0.99      0.94      0.96       371
       P2293       1.00      1.00      1.00       173
         P86       1.00      1.00      1.00        38
         P97       1.00      1.00      1.00        98
        P195       1.00      1.00      1.00         4
        P427       1.00      0.44      0.62         9
         P84       1.00      1.00      1.00        62
        P103       1.00      1.00      1.00       816
        P272       1.00      1.00      1.00         2
        P689       1.00      1.00      1.00         2
         P61       1.00      1.00      1.00       531
        P237       1.00      1.00      1.00        65
        P674       1.00      1.00      1.00        22
       P2348       1.00      1.00      1.00         1
        P737       1.00      1.00      1.00        44
         P38       1.00      1.00      1.00         9
         P88       1.00      1.00      1.00       116
       P1303       0.52      1.00      0.69        22
        P201       1.00      1.00      1.00         7
        P437       1.00      1.00      1.00         2
        P306       1.00      1.00      1.00       156
        P178       1.00      1.00      1.00        18
        P825       1.00      0.80      0.89       438
       P1056       1.00      1.00      1.00        63
       P1408       1.00      1.00      1.00        28
        P530       1.00      1.00      1.00        28
        P629       1.00      1.00      1.00        34
       P1433       1.00      0.96      0.98        23
        P122       0.98      1.00      0.99        63
       P1444       0.99      1.00      1.00       483
        P559       1.00      1.00      1.00       137
        P941       1.00      1.00      1.00         1
        P974       1.00      0.75      0.86         4
        P451       1.00      1.00      1.00       576
        P287       1.00      1.00      1.00         6
        P277       1.00      0.93      0.96        14
        P184       1.00      1.00      1.00        41
        P485       0.99      1.00      1.00       500
        P407       0.99      1.00      1.00       171
        P449       1.00      1.00      1.00        28
        P183       1.00      1.00      1.00       160
       P2695       1.00      1.00      1.00       159
       P1533       1.00      1.00      1.00         7
       P1383       1.00      1.00      1.00         3
        P828       1.00      0.95      0.97        61
        P282       1.00      1.00      1.00        66
        P135       1.00      1.00      1.00        10
       P1990       1.00      1.00      1.00       773
        P469       1.00      1.00      1.00       271
       P1427       1.00      1.00      1.00        18
        P110       1.00      1.00      1.00         1
        P398       1.00      1.00      1.00       333
        P157       1.00      1.00      1.00       229
       P3085       1.00      1.00      1.00       143
        P413       0.99      1.00      0.99       270
        P647       1.00      1.00      1.00         7
        P197       1.00      1.00      1.00        47
        P411       1.00      1.00      1.00        58
        P725       1.00      1.00      1.00       309
        P870       1.00      0.98      0.99        46
        P189       1.00      1.00      1.00        12
        P126       1.00      1.00      1.00         3
       P1431       0.95      1.00      0.97      1462
       P2176       1.00      1.00      1.00        10
        P488       1.00      1.00      1.00         2
        P121       1.00      1.00      1.00         3
        P608       1.00      1.00      1.00        28
         P98       1.00      0.77      0.87        13
       P1884       1.00      1.00      1.00        34
       P1750       1.00      0.96      0.98        23
       P1923       1.00      1.00      1.00       213
        P841       0.97      1.00      0.99       560
        P669       1.00      1.00      1.00       290
         P81       1.00      1.00      1.00       107
        P376       0.73      1.00      0.84       544
        P403       1.00      1.00      1.00        49
        P200       1.00      1.00      1.00       698
        P193       1.00      0.72      0.83       700
        P408       1.00      1.00      1.00       880
        P520       0.97      0.98      0.97        59
       P1192       0.98      0.94      0.96       239
       P1403       1.00      1.00      1.00         7
       P3179       0.89      1.00      0.94       660
        P421       1.00      1.00      1.00       211
        P371       1.00      1.00      1.00        52
        P177       1.00      0.99      1.00       214
        P289       1.00      1.00      1.00        14
        P516       0.95      0.84      0.89        43
        P196       1.00      1.00      1.00        87
       P1382       1.00      1.00      1.00         5
        P658       1.00      1.00      1.00         6
        P115       1.00      1.00      1.00         8
        P169       1.00      1.00      1.00         1
        P504       1.00      1.00      1.00        97
       P1028       1.00      1.00      1.00       208
       P2860       1.00      0.85      0.92        74
       P1399       1.00      1.00      1.00         1
        P636       1.00      1.00      1.00        13
        P532       1.00      1.00      1.00         1
        P397       1.00      1.00      1.00        25
        P837       0.92      1.00      0.96        24
       P3091       1.00      1.00      1.00         1
        P790       0.97      0.93      0.95        40
        P655       1.00      1.00      1.00       247
        P769       1.00      1.00      1.00        17
        P566       1.00      1.00      1.00       237
       P1037       1.00      1.00      1.00        43
       P2522       1.00      1.00      1.00       232
        P248       1.00      1.00      1.00        18
       P2632       1.00      1.00      1.00        51
         P16       1.00      1.00      1.00       197
        P404       1.00      1.00      1.00       404
       P1445       1.00      1.00      1.00        85
       P3195       1.00      1.00      1.00       638
       P2079       1.00      1.00      1.00        24
        P467       1.00      1.00      1.00        41
       P1462       1.00      1.00      1.00        12
        P812       1.00      0.71      0.83        14
        P805       1.00      1.00      1.00        39

    accuracy                           0.98     44438
   macro avg       0.98      0.97      0.97     44438
weighted avg       0.98      0.98      0.98     44438

In [133]:
f = open('rulebase_report','w')
print(classification_report(gold_preds, rule_preds, target_names=uniq_tagset), file=f)